apiVersion: v1
kind: Service
metadata:
  namespace: workshop
  name: mongodb-svc
spec:
  selector:
    app: mongodb
  ports:
  - name: mongodb-svc  #serviceName
    protocol: TCP
    port: 27017
    targetPort: 27017